app_id = ""

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = ""
name = "host"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "make"

  # xtp plugin init runs this script to format the plugin code
  format = "make format"

  # xtp plugin init runs this script before running the format script
  prepare = ""
